obstacle_range: 2.5
raytrace_range: 3.0
footprint: [x0, y0]
#robot_radius: ir_of_robot
inflation_radius: 0.7
footprint: [[-0.12, -0.08], [-0.12, 0.08], [0.12, 0.08], [0.12, -0.08]]
footprint_padding: 0.0
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 4.0
transform_tolerance: 0.5
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
