global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 4.0
  static_map: true
  rolling_window: false
  width: 12.0
  height: 12.0
  resolution: 0.12

